language: node_js
node_js:
  - "0.10"

services:
  - mongodb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - 'npm install -g bower grunt-cli karma'
  - 'bower install'
  - sleep 1 # give server time to start

script:
  - ./node_modules/karma/bin/karma start test/unit/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
