language: node_js
node_js:
  - "0.10"

services:
  - mongodb

before_script:
  - export DISPLAY=:99.0
  - nodemon &
  - webdriver-manager start --standalone
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start test/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor e2e/conf.js --browser=PhantomJS